/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lcdp.bank;

import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static lcdp.bank.Bank.b;

/**
 *
 * @author as
 */
public class CHECKSTATUSPAGE extends javax.swing.JFrame {

    /**
     * Creates new form CHECKSTATUSPAGE
     */

    public CHECKSTATUSPAGE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LOGOUTCS = new javax.swing.JButton();
        BACKTOMENUCS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BORROWED = new javax.swing.JTextField();
        AVALIABLECREDIT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TIMELEFT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        LOGOUTCS.setBackground(new java.awt.Color(85, 5, 14));
        LOGOUTCS.setFont(new java.awt.Font("Compacta BT", 0, 24)); // NOI18N
        LOGOUTCS.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUTCS.setText("LOG OUT");
        LOGOUTCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTCSActionPerformed(evt);
            }
        });
        jPanel1.add(LOGOUTCS);
        LOGOUTCS.setBounds(450, 20, 130, 40);

        BACKTOMENUCS.setBackground(new java.awt.Color(85, 5, 14));
        BACKTOMENUCS.setFont(new java.awt.Font("Compacta BT", 0, 24)); // NOI18N
        BACKTOMENUCS.setForeground(new java.awt.Color(255, 255, 255));
        BACKTOMENUCS.setText("BACK TO MENU");
        BACKTOMENUCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKTOMENUCSActionPerformed(evt);
            }
        });
        jPanel1.add(BACKTOMENUCS);
        BACKTOMENUCS.setBounds(270, 20, 170, 40);

        jLabel2.setFont(new java.awt.Font("Compacta BT", 0, 24)); // NOI18N
        jLabel2.setText("THE AMOUNT BORROWED");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 350, 170, 80);

        BORROWED.setEditable(false);
        BORROWED.setFont(new java.awt.Font("Compacta BT", 0, 18)); // NOI18N
        BORROWED.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BORROWED.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 5, 14), 4));
        BORROWED.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BORROWED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORROWEDActionPerformed(evt);
            }
        });
        jPanel1.add(BORROWED);
        BORROWED.setBounds(160, 410, 420, 40);

        AVALIABLECREDIT.setEditable(false);
        AVALIABLECREDIT.setFont(new java.awt.Font("Compacta BT", 0, 18)); // NOI18N
        AVALIABLECREDIT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AVALIABLECREDIT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 5, 14), 4));
        AVALIABLECREDIT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AVALIABLECREDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AVALIABLECREDITActionPerformed(evt);
            }
        });
        jPanel1.add(AVALIABLECREDIT);
        AVALIABLECREDIT.setBounds(160, 320, 420, 40);

        jLabel3.setFont(new java.awt.Font("Compacta BT", 0, 24)); // NOI18N
        jLabel3.setText("AVAILABLE CREDIT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 260, 170, 80);

        jLabel4.setFont(new java.awt.Font("Compacta BT", 0, 24)); // NOI18N
        jLabel4.setText("TIME LEFT");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 440, 170, 80);

        TIMELEFT.setEditable(false);
        TIMELEFT.setFont(new java.awt.Font("Compacta BT", 0, 18)); // NOI18N
        TIMELEFT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TIMELEFT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 5, 14), 4));
        TIMELEFT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TIMELEFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIMELEFTActionPerformed(evt);
            }
        });
        jPanel1.add(TIMELEFT);
        TIMELEFT.setBounds(160, 500, 420, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lcdp/bank/CHECKSTATUSPAGE.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGOUTCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTCSActionPerformed
        try {
            new LOGIN().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(CHECKSTATUSPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_LOGOUTCSActionPerformed

    private void BACKTOMENUCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKTOMENUCSActionPerformed
      MENU m = new MENU();
      String s1 = b[Bank.i].getFirstname();
      String s2 = b[Bank.i].getLastname();
      m.setVisible(true);
      m.jLabel2.setText("Hello"+"  "+s1+" "+s2);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_BACKTOMENUCSActionPerformed

    private void BORROWEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORROWEDActionPerformed
        
    }//GEN-LAST:event_BORROWEDActionPerformed

    private void AVALIABLECREDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AVALIABLECREDITActionPerformed
  
    }//GEN-LAST:event_AVALIABLECREDITActionPerformed

    private void TIMELEFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIMELEFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIMELEFTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHECKSTATUSPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHECKSTATUSPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHECKSTATUSPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHECKSTATUSPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHECKSTATUSPAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField AVALIABLECREDIT;
    private javax.swing.JButton BACKTOMENUCS;
    public static javax.swing.JTextField BORROWED;
    private javax.swing.JButton LOGOUTCS;
    public static javax.swing.JTextField TIMELEFT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
