/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lcdp.bank;

import java.awt.event.WindowEvent;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import static lcdp.bank.Bank.b;


/**
 *
 * @author as
 */
public class LOGIN extends javax.swing.JFrame{
  Bank1 j = new Bank1();
////  public Bank1 []b = j.load();
//  public static int i;
//   static Bank1 []b;
//    
//public void setB(Bank1[] b) throws IOException {
//        this.b = b;
//        this.b = j.load();
//    }
  
 
    public LOGIN() throws IOException {
          
       
    
        initComponents();}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LOGINBUTTON = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        USERPASSWORD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        USERLOGIN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setLayout(null);

        LOGINBUTTON.setBackground(new java.awt.Color(85, 5, 14));
        LOGINBUTTON.setFont(new java.awt.Font("Compacta BT", 0, 24)); // NOI18N
        LOGINBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        LOGINBUTTON.setText("LOG IN");
        LOGINBUTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOGINBUTTONMouseClicked(evt);
            }
        });
        LOGINBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINBUTTONActionPerformed(evt);
            }
        });
        LOGINBUTTON.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LOGINBUTTONKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LOGINBUTTONKeyTyped(evt);
            }
        });
        jPanel1.add(LOGINBUTTON);
        LOGINBUTTON.setBounds(240, 570, 130, 40);

        jLabel3.setFont(new java.awt.Font("Compacta BT", 0, 24)); // NOI18N
        jLabel3.setText("PASSWORD");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 440, 170, 80);

        USERPASSWORD.setFont(new java.awt.Font("Bookshelf Symbol 7", 0, 26)); // NOI18N
        USERPASSWORD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 5, 14), 4));
        USERPASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERPASSWORDActionPerformed(evt);
            }
        });
        USERPASSWORD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                USERPASSWORDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                USERPASSWORDKeyReleased(evt);
            }
        });
        jPanel1.add(USERPASSWORD);
        USERPASSWORD.setBounds(90, 500, 420, 40);

        jLabel2.setFont(new java.awt.Font("Compacta BT", 0, 24)); // NOI18N
        jLabel2.setText("USER");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 350, 170, 80);

        USERLOGIN.setFont(new java.awt.Font("Compacta BT", 0, 18)); // NOI18N
        USERLOGIN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(85, 5, 14), 4));
        USERLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERLOGINActionPerformed(evt);
            }
        });
        USERLOGIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                USERLOGINKeyPressed(evt);
            }
        });
        jPanel1.add(USERLOGIN);
        USERLOGIN.setBounds(90, 410, 420, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lcdp/bank/5.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGINBUTTONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LOGINBUTTONKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINBUTTONKeyTyped

    private void USERLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERLOGINActionPerformed
    

    }//GEN-LAST:event_USERLOGINActionPerformed

    private void USERPASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERPASSWORDActionPerformed

    }//GEN-LAST:event_USERPASSWORDActionPerformed

    private void LOGINBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINBUTTONActionPerformed
         if(  USERPASSWORD.getText().isEmpty()|| USERLOGIN.getText().isEmpty()){
             new NOINPUT().setVisible(true);
         }
         else{
  if(j.checkCreditb(Integer.parseInt( USERLOGIN.getText()), Integer.parseInt( USERPASSWORD.getText()), b)){
        
       Bank.i = j.checkCredit(Integer.parseInt( USERLOGIN.getText()), Integer.parseInt( USERPASSWORD.getText()), b);
       String user = USERLOGIN.getText();
       int numberofchars = user.length();
       if (numberofchars == 6){
       Bank.flag = true;
       }
       
       else {
       Bank.flag = false;
       
       }
       if (!b[Bank.i].getLaststatus()){
      MENU m = new MENU();
      String s1 = b[Bank.i].getFirstname();
      String s2 = b[Bank.i].getLastname();
      m.setVisible(true);
      m.jLabel2.setText("Hello"+"  "+s1+" "+s2);
       }
       else{
            new CLOSED().setVisible(true);
           this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
       }
      
  this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
  }else{

      INVALID i = new INVALID();
      i.setVisible(true);
     this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
  }
         }
    }//GEN-LAST:event_LOGINBUTTONActionPerformed

    private void LOGINBUTTONKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LOGINBUTTONKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINBUTTONKeyPressed

    private void LOGINBUTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOGINBUTTONMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGINBUTTONMouseClicked

    private void USERPASSWORDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERPASSWORDKeyPressed
char C = evt.getKeyChar();
String user = USERPASSWORD.getText();
int length = user.length();

        if(Character.isISOControl(C)||(Character.isDigit(C) && length<=8 )){
    USERPASSWORD.setEditable(true);
   
   }

else{
     USERPASSWORD.setEditable(false);
}               
    }//GEN-LAST:event_USERPASSWORDKeyPressed

    private void USERLOGINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERLOGINKeyPressed
char C = evt.getKeyChar();
String user = USERLOGIN.getText();
int length = user.length();

        if(Character.isISOControl(C)||(Character.isDigit(C) && length<=8 )){
    USERLOGIN.setEditable(true);
   
   }

else{
     USERLOGIN.setEditable(false);
}               
   
    }//GEN-LAST:event_USERLOGINKeyPressed

    private void USERPASSWORDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_USERPASSWORDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_USERPASSWORDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LOGIN().setVisible(true);
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton LOGINBUTTON;
    public static javax.swing.JTextField USERLOGIN;
    public static javax.swing.JTextField USERPASSWORD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
